package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_SIGNAL extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SIGNAL() {
    super(0x6d84bad7eb044249L, 0x8d80c9157947c3f2L, 0x1ee64324e96f0fc8L, "SIGNAL", "r:95dc3936-047b-4df0-883d-ba757a2402dd(ArduinoML.structure)/2226540891595542472", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "high", "r:95dc3936-047b-4df0-883d-ba757a2402dd(ArduinoML.structure)/2226540891595542473", "HIGH");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "low", "r:95dc3936-047b-4df0-883d-ba757a2402dd(ArduinoML.structure)/2226540891595542474", "LOW");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_HIGH_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_HIGH_0, VALUE_LOW_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "HIGH":
        return VALUE_HIGH_0;
      case "LOW":
        return VALUE_LOW_0;
    }
    return null;
  }
}
